language: php
#php:
#  - 5.5
#  - 5.4
#  - hhvm
#script: phpunit Test.php
script: aws opsworks --region us-east-1 create-deployment --stack-id e07831df-bdf5-4855-a593-9f7dee8d5612 --app-id 282d2ffb-09e8-43f0-bdef-850997fb238d --command "{\"Name\":\"deploy\"}"

deploy:
  provider: opsworks
  access-key-id: AKIAJW75BZSVGHFF4TNA
  secret-access-key:
    secure: Nt9LQ+QL8EDNfaKjcYxXHIrF7XtJ4mo2gTnl8x24HUivWzKx6HhwbTTwTNmagaDLPVAr5lNIpP3PR0GcLWGOzoBrtA+s6q+o+Cs29yZlIk2n9cPxGDSqnJ6VF2GIuuHV3vq/heMPbLfynyk0CQ5LSD02LNbqb4OO9pCx7lPTcyc7h4xbdxAxdlzqIEPxijZ878AnEA8zHYzzqNMcxAtDwAHoynSsUPB++DDrmWzHLGIthsF7m/bu8Khos936B2YCUDl8PNMZHbPQRvsxWHZfpxgBR2XUm7liynPivPgtal0gcJuC62fxD1l+TIO7VQPLoUgNvS0jqKk62aUS7gI8vpHovgf52eGpejWxilAXbyqaG+Yc39KEwsoT/PJJVKiO3nbnEK1rrzSw9TKppORKMTb3Gpy7CO3LzbT3z1Cf2X41aCL2j00ono/MRV+5uqoBpuMUK6xcMHvQmXJvpBI+9pZWVQcP2UQd629YJlI5usEAkI2WoE+Go8BHD13F/6O7ZnRECfpMw1qUoc1PaKwDxCtWu6NDrGU/dcMhbh6BskabW6jKaQxlmlfRvMupuV4UDJIFn1ewn3CEVPnFjLtcxiIZCOm/C9MiVlBRa7vlwMW8pn/ovmiMJHdmLl6FzaJvvZMYRAdePc6fzev6764SxTfOdlGi9n6ac8xbfpUGYhI=
  app-id: 282d2ffb-09e8-43f0-bdef-850997fb238d
  on:
    repo: sohiljain/docker-opsworks
    
# Email specific recipient all the time
#notifications:
#  email:
#    recipients:
#      - sohiljain.cs91@gmail.com
#  on_success: always # default: change
